adventurebook: yenisei.cpp tiling.h enemy.h enemy.cpp louis.h louis.cpp renderer.h renderer.cpp level1.cpp convert.cpp cutscenes.cpp cutscenes.h button.h button.cpp collision.cpp battle.h battle.cpp text.h text.cpp objects.h objects.cpp background.h background.cpp projectiles.h projectiles.cpp
	g++ yenisei.cpp -w -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -o yenisei
	g++ convert.cpp -w -o convert
